# Config designed to maximize recall
data:
  root_dir: data
  rating_threshold: 3.5    # 3.5+ star ratings (still selective but not too strict)
split:
  holdout_per_user: 15     # Hold out 15 items per user (many targets!)
  min_interactions: 25     # Active users only
training:
  seed: 42
  device: cpu
  batch_size: 1024
  epochs: 20
  lr: 0.001
  embedding_dim: 128
eval:
  k: 10
  exclude_train_items: true
artifacts:
  dir: artifacts/movielens_small_twotower_max_recall
  faiss_index: index.faiss
  model_file: model.pt
  user_map: user_id_map.json
  item_map: item_id_map.json
  metrics_file: metrics.json